apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
    name: prometheus
    namespace: monitoring
spec:
    serviceAccountName: prometheus
    serviceMonitorSelector: {}
    resources:
        requests:
            memory: 300Mi
    serviceMonitorNamespaceSelector: {}
