apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    labels:
        name: prometheus
    name: prometheus
    namespace: monitoring
spec:
    endpoints:
        - interval: 30s
          targetPort: 9090
          path: /metrics
    namespaceSelector:
        matchNames:
          - my-django-namespace
    selector:
        matchLabels:
            operated-prometheus: "true"
