apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-django-servicemonitor
  namespace: monitoring
  labels:
    name: prometheus 
spec:
  namespaceSelector:
    matchNames:
      - my-django-namespace
      
  selector:
    matchLabels:
      app: my-django-service
      
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s