---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-deployment
  labels:
    app: my-django-app
  namepsace: my-django-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-django-app
  template:
    metadata:
      labels:
        app: my-django-app
    spec:
      containers:
        - name: my-django-container
          image: tpchungg/my_django_app:444c70f07a515cb527fc3e300ce868298f4b2fc1
          imagePullPolicy: Always
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-django-service
  namespace: my-django-namespace
  labels:
    app: my-django-service
spec:
  type: ClusterIP
  selector:
    app: my-django-app
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 7070